### ISSUE TITLE
Test in LXC

### ISSUE THREAD

**Issue by jpic** [nylas/ansible-test#3]
Nice package !

Have you considered running tests in a LXC guests ? LXC may be a better tool because it does distribution isolation, rather than process isolation: it runs a real init as PID 1.

You could run something like this to create the LXC guests the test needs from the test inventory file:

```
- hosts: localhost
  vars:
    LXC_PATH: /var/lib/lxc  # change to /tmp to run in ram with -e

  tasks:
  - name: Configure container
    lxc_container:
      name: '{{ item }}'
      template: debian
      state: started
      template_options: --release wheezy
      lxc_path: '{{ LXC_PATH }}'
    with_items: '{{ groups["all"] }}'

  - name: Ensure .ssh directory exists in container
    file:
      path: '{{ LXC_PATH }}/{{ item }}/.ssh'
      state: directory
      mode: 0700
    with_items: '{{ groups["all"] }}'

  - name: Add your SSH key in the container
    copy:
      src: '{{ lookup("env", "HOME") }}/.ssh/id_rsa.pub'
      dest: '{{ LXC_PATH }}/{{ item }}/.ssh/authorized_keys'
      mode: 0600
    with_items: '{{ groups["all"] }}'
```

Then you could execute your playbooks from the host.

Testing on multiple hosts may be useful for more complicated tests such as orchestration tests.

Thoughts ?
